import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Link from 'next/link'

export default function Home({ posts }: { posts: any }) {
  return (
    <div>
      <Head>
        <title>docs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="mt-5 pr-300 px-20">
        {posts.map((post: any, index: any) => {
          console.log()
          const img = post.frontMatter.thumbnailUrl
          return (
            <Link href={'/blog/' + post.slug} passHref key={index}>
              <div className=" bg-gray-400 px-20 py-20 mb-20 rounded-4 transition-all hover:bg-skin-900">
                <div className="font-bold text-28">{post.frontMatter.title}</div>
                <em className="">{post.frontMatter.description}</em>
                {post.frontMatter.thumbnailUrl && <div className="mt-10">
                  <Image
                    src={img}
                    alt=""
                    width={500}
                    height={400}
                    objectFit="cover"
                  />
                </div>}
                <div className="mt-10 text-10">{post.frontMatter.date}</div>

              </div>
            </Link>
          )
        })}
      </div>
    </div>
  )
}
export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('posts'))
  const posts = files.map(filename => {
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8')
    const { data: frontMatter } = matter(markdownWithMeta)
    return {
      frontMatter,
      slug: filename.split('.')[0]
    }
  })
  return {
    props: {
      posts
    }
  }
}