import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Index.module.scss';
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Link from 'next/link'
import { useState } from 'react'
import classnames from 'classnames';


export default function Index({ posts,mathPosts,gamePosts,otherPosts }: { posts: any,mathPosts:any,gamePosts:any,otherPosts:any }) {
  const [type, setType] = useState('post');
  const tabbar = [
    {
      name:'Home',
      key:'post'
    },
    {
      name:'Math',
      key:'math'
    },
    {
      name:'Game',
      key:'game'
    },
    {
      name:'Archive',
      key:'other'
    },
  ]
  return (
    <div>
      <Head>
        <title>docs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="mt-5 pr-500 px-20">
        {type==="post"&&posts.map((post: any, index: any) => {
          console.log()
          const img = post.frontMatter.thumbnailUrl
          return (
            <Link href={'/blog/' + post.slug} passHref key={index}>
              <div className=" px-20 py-20 mb-20 rounded-4 transition-all hover:bg-skin-900 shadow-xl">
                <div className="font-bold text-28">{post.frontMatter.title}</div>
                <em className="">{post.frontMatter.description}</em>
                {post.frontMatter.thumbnailUrl && <div className="mt-10">
                  <Image
                    src={img}
                    alt=""
                    width={500}
                    height={400}
                    objectFit="cover"
                  />
                </div>}
                <div className="mt-10 text-10">{post.frontMatter.date}</div>
                <div className="mt-5 text-10">by：{post.frontMatter.author}</div>
              </div>
            </Link>
          )
        })}
        {type==="math"&&mathPosts.map((post: any, index: any) => {
          console.log()
          const img = post.frontMatter.thumbnailUrl
          return (
            <Link href={'/blog/' + post.slug} passHref key={index}>
              <div className=" px-20 py-20 mb-20 rounded-4 transition-all hover:bg-skin-900 shadow-xl">
                <div className="font-bold text-28">{post.frontMatter.title}</div>
                <em className="">{post.frontMatter.description}</em>
                {post.frontMatter.thumbnailUrl && <div className="mt-10">
                  <Image
                    src={img}
                    alt=""
                    width={500}
                    height={400}
                    objectFit="cover"
                  />
                </div>}
                <div className="mt-10 text-10">{post.frontMatter.date}</div>
                <div className="mt-5 text-10">by：{post.frontMatter.author}</div>
              </div>
            </Link>
          )
        })}
        {type==="game"&&gamePosts.map((post: any, index: any) => {
          console.log()
          const img = post.frontMatter.thumbnailUrl
          return (
            <Link href={'/blog/' + post.slug} passHref key={index}>
              <div className=" px-20 py-20 mb-20 rounded-4 transition-all hover:bg-skin-900 shadow-xl">
                <div className="font-bold text-28">{post.frontMatter.title}</div>
                <em className="">{post.frontMatter.description}</em>
                {post.frontMatter.thumbnailUrl && <div className="mt-10">
                  <Image
                    src={img}
                    alt=""
                    width={500}
                    height={400}
                    objectFit="cover"
                  />
                </div>}
                <div className="mt-10 text-10">{post.frontMatter.date}</div>
                <div className="mt-5 text-10">by：{post.frontMatter.author}</div>
              </div>
            </Link>
          )
        })}
        {type==="other"&&otherPosts.map((post: any, index: any) => {
          console.log()
          const img = post.frontMatter.thumbnailUrl
          return (
            <Link href={'/blog/' + post.slug} passHref key={index}>
              <div className=" px-20 py-20 mb-20 rounded-4 transition-all hover:bg-skin-900 shadow-xl">
                <div className="font-bold text-28">{post.frontMatter.title}</div>
                <em className="">{post.frontMatter.description}</em>
                {post.frontMatter.thumbnailUrl && <div className="mt-10">
                  <Image
                    src={img}
                    alt=""
                    width={500}
                    height={400}
                    objectFit="cover"
                  />
                </div>}
                <div className="mt-10 text-10">{post.frontMatter.date}</div>
                <div className="mt-5 text-10">by：{post.frontMatter.author}</div>
              </div>
            </Link>
          )
        })}
      </div>
      <div className="fixed right-50 text-20 top-200 flex flex-col justify-between" style={{height:'50%'}}>
        {
          tabbar.map(item=>{
            return (
              <div className='flex items-center'>
                <div className={classnames(item.key===type?'text-skin-900':'text-white',styles.tabText)} onClick={()=>setType(item.key)}>{item.name}</div>
                {item.key===type&&<div className='h-20 w-4 bg-skin-900 mt-2'></div>}
              </div>
              
            )
          })
        }
      </div>
    </div>
  )
}
export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('posts'));
  const posts = files.map(filename => {
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8');
    const { data: frontMatter } = matter(markdownWithMeta);
    return {
      frontMatter,
      slug: filename.split('.')[0]
    }
  })
  const mathFiles = fs.readdirSync(path.join('maths'));
  const mathPosts = mathFiles.map(filename => {
    const markdownWithMeta = fs.readFileSync(path.join('maths', filename), 'utf-8');
    const { data: frontMatter } = matter(markdownWithMeta);
    return {
      frontMatter,
      slug: filename.split('.')[0]
    }
  })
  const gameFiles = fs.readdirSync(path.join('games'));
  const gamePosts = gameFiles.map(filename => {
    const markdownWithMeta = fs.readFileSync(path.join('games', filename), 'utf-8');
    const { data: frontMatter } = matter(markdownWithMeta);
    return {
      frontMatter,
      slug: filename.split('.')[0]
    }
  })
  const otherFiles = fs.readdirSync(path.join('others'));
  const otherPosts = otherFiles.map(filename => {
    const markdownWithMeta = fs.readFileSync(path.join('others', filename), 'utf-8');
    const { data: frontMatter } = matter(markdownWithMeta);
    return {
      frontMatter,
      slug: filename.split('.')[0]
    }
  })
  return {
    props: {
      posts,
      mathPosts,
      gamePosts,
      otherPosts
    }
  }
}